### ISSUE TITLE
Won't play shared links (Yatse)

### ISSUE THREAD

**Issue by malolookan** [jaylinski/kodi-addon-soundcloud#64] opened 2023-12-27 14:37 UTC
Since I updated Kodi to Nexus it won't play shared links anymore through the YATSE app.
I added the error log to the issue.
[Soundcloud_PluginError.log](https://github.com/jaylinski/kodi-addon-soundcloud/files/13779289/Soundcloud_PluginError.log)

Thanks for the support!

**Comment by malolookan** [comment] 2023-12-27 14:39
This is the content of the log:

2023-12-27 15:18:43.747 T:28521    info <general>: Skipped 1 duplicate messages..
2023-12-27 15:18:43.747 T:28521   error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'RuntimeError'>
                                                   Error Contents: ApiV2 JSON seems to be invalid
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.audio.soundcloud/addon.py", line 3, in <module>
                                                       plugin.run()
                                                     File "/storage/.kodi/addons/plugin.audio.soundcloud/resources/plugin.py", line 101, in run
                                                       collection = listItems.from_collection(api.resolve_url(url))
                                                                                              ^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 92, in resolve_url
                                                       return self._map_json_to_collection(res)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/.kodi/addons/plugin.audio.soundcloud/resources/lib/soundcloud/api_v2.py", line 221, in _map_json_to_collection
                                                       raise RuntimeError("ApiV2 JSON seems to be invalid")
                                                   RuntimeError: ApiV2 JSON seems to be invalid
                                                   -->End of Python script error report<--

**Comment by malolookan** [comment] 2023-12-27 14:51
Fixed it by installing the Yatse Helper Script on Kodi.
However, resolving the URL takes a lot of time. Stream starts approximately 20 seconds after the command to play the link.

**Comment by jaylinski** [comment] 2023-12-29 18:21
Thanks for reporting. I'll take a look at it.

**Comment by jaylinski** [comment] 2024-03-14 22:11
> Stream starts approximately 20 seconds after the command to play the link

This only happens when using Yatse? In this case, I guess the issue is in the Yatse Helper Script, since there is a lot of stuff happening: https://github.com/Tolriq/repository.yatse.kodi/blob/master/script.yatse.kodi/lib/youtube_dl/extractor/soundcloud.py

**Comment by jaylinski** [comment] 2024-04-05 18:40
Closing because there is a workaround and the issue is probably not caused by this addon.

**Closed by jaylinski** 2024-04-05 18:40 UTC
